#!/usr/bin/env node
// Generates web/ds-src/ -- the design-system entry this application does not have.
//
// nexus-assets is an app, not a component library: package.json is private, with
// no main/module/exports, and dist/ is an app build. The converter's fallback is
// to synthesize an entry from every .tsx under srcDir, which here means every
// route and main.tsx -- and main.tsx imports index.css, whose `@import
// "tailwindcss"` esbuild cannot resolve. So instead of pointing srcDir at all of
// src/, we point it at a small generated tree of barrels that name exactly the
// surface we intend to publish.
//
// ts-morph's getExportedDeclarations() follows re-exports, so component
// discovery sees through these barrels to the real declarations; esbuild only
// pulls what they name. One barrel per group so a regroup is a line here.
//
// Regenerated by cfg.buildCmd on every sync -- never hand-edit web/ds-src/.
import { mkdirSync, rmSync, writeFileSync, readdirSync } from 'node:fs'
import { join, relative, dirname } from 'node:path'
import { fileURLToPath } from 'node:url'

const WEB = join(dirname(fileURLToPath(import.meta.url)), '..', 'web')
const OUT = join(WEB, 'ds-src')

/** The published surface, by group. Directories take every .tsx they hold. */
const GROUPS = {
  // shadcn/ui, restyled to Organic in 017. The primitives everything else is
  // built from; sub-parts (DialogHeader, CardContent, ...) come with them.
  ui: { dir: 'src/components/ui' },
  // The parts this application added on top -- page chrome, list plumbing.
  // These are what make a design read as Nexus rather than as plain shadcn.
  common: { dir: 'src/features/common' },
  overview: { dir: 'src/features/overview' },
  data: {
    files: [
      'src/components/StateBoundary.tsx',
      'src/features/statuses/StatusBadge.tsx',
      'src/features/transfers/Timeline.tsx',
      'src/features/metadata/CrudPage.tsx',
      'src/features/metadata/MetadataTabs.tsx',
    ],
  },
}

rmSync(OUT, { recursive: true, force: true })
mkdirSync(OUT, { recursive: true })

let total = 0
for (const [group, spec] of Object.entries(GROUPS)) {
  const files = spec.dir
    ? readdirSync(join(WEB, spec.dir))
        .filter((n) => n.endsWith('.tsx') && !/\.(test|stories|spec)\./.test(n))
        .map((n) => join(spec.dir, n))
    : spec.files
  const body = files
    .map((f) => `export * from ${JSON.stringify('../' + f.replace(/\.tsx$/, ''))}`)
    .join('\n')
  writeFileSync(join(OUT, `${group}.tsx`), `${body}\n`)
  total += files.length
  console.error(`  ${group}.tsx: ${files.length} modules`)
}
// The converter reads the package's .d.ts entry as each component's API
// contract, falling back to <pkgDir>/index.d.ts when package.json names no
// `types`. Writing that fallback here means the app's package.json stays
// untouched -- a `types` field added for a tool would outlive the tool.
const groups = Object.keys(GROUPS)
writeFileSync(
  join(WEB, 'index.d.ts'),
  `// Generated by .design-sync/make-ds-src.mjs -- the declaration entry the design-system\n` +
    `// converter reads. Regenerated on every sync; gitignored; nothing else imports it.\n` +
    groups.map((g) => `export * from './.ds-types/ds-src/${g}'`).join('\n') +
    '\n',
)
console.error(`web/ds-src: ${groups.length} barrels over ${total} modules (+ index.d.ts)`)
